#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AlmueAndroid.Resource", IsApplication=true)]

namespace AlmueAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int feed_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int feed_item_bg = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int feed_item_border = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int link = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int timestamp = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int control_buttons_height = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int control_buttons_paddingTop = 2131099653;
			
			// aapt resource value: 0x7f060011
			public const int feed_item_border_width = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int feed_item_corner_radius = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int feed_item_margin = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int feed_item_padding_left_right = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int feed_item_padding_top_bottom = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int feed_item_profile_info_padd = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int feed_item_profile_name = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int feed_item_profile_pic = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int feed_item_status_pad_left_right = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int feed_item_status_pad_top = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int feed_item_timestamp = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int text_large = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int text_small = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int text_xlarge = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AlmueLogo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_parent_rounded_corner = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_file_download_black_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_file_upload_black_24dp = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_lightbulb_outline_black_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_line_weight_black_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_stop_black_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000a
			public const int CloseButton = 2131296266;
			
			// aapt resource value: 0x7f090007
			public const int about_credits = 2131296263;
			
			// aapt resource value: 0x7f09000f
			public const int btnEnableDisableShutter = 2131296271;
			
			// aapt resource value: 0x7f090016
			public const int btnEnableDisableTimer = 2131296278;
			
			// aapt resource value: 0x7f090004
			public const int btnLogin = 2131296260;
			
			// aapt resource value: 0x7f090013
			public const int btnShutterDown = 2131296275;
			
			// aapt resource value: 0x7f090012
			public const int btnShutterStop = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int btnShutterUp = 2131296273;
			
			// aapt resource value: 0x7f090003
			public const int chkSaveLoginData = 2131296259;
			
			// aapt resource value: 0x7f09001e
			public const int deviceDescription = 2131296286;
			
			// aapt resource value: 0x7f090006
			public const int deviceFragmentContainer = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int deviceImage = 2131296267;
			
			// aapt resource value: 0x7f09001d
			public const int devicesListView = 2131296285;
			
			// aapt resource value: 0x7f09001a
			public const int linlayTimes = 2131296282;
			
			// aapt resource value: 0x7f090017
			public const int linlayTimesLabels = 2131296279;
			
			// aapt resource value: 0x7f090022
			public const int menuAbout = 2131296290;
			
			// aapt resource value: 0x7f090020
			public const int menuCloseAll = 2131296288;
			
			// aapt resource value: 0x7f090023
			public const int menuExit = 2131296291;
			
			// aapt resource value: 0x7f090021
			public const int menuLogout = 2131296289;
			
			// aapt resource value: 0x7f09001f
			public const int menuOpenAll = 2131296287;
			
			// aapt resource value: 0x7f090005
			public const int pgBar = 2131296261;
			
			// aapt resource value: 0x7f090008
			public const int textView1 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int textView2 = 2131296265;
			
			// aapt resource value: 0x7f090000
			public const int txtBroker = 2131296256;
			
			// aapt resource value: 0x7f090019
			public const int txtCloseTime = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int txtEnableDisableTimer = 2131296277;
			
			// aapt resource value: 0x7f090018
			public const int txtOpenTime = 2131296280;
			
			// aapt resource value: 0x7f090002
			public const int txtPw = 2131296258;
			
			// aapt resource value: 0x7f09000c
			public const int txtShutterDescription = 2131296268;
			
			// aapt resource value: 0x7f09000e
			public const int txtShutterEnableDisable = 2131296270;
			
			// aapt resource value: 0x7f09000d
			public const int txtShutterFloor = 2131296269;
			
			// aapt resource value: 0x7f090010
			public const int txtShutterStatus = 2131296272;
			
			// aapt resource value: 0x7f09001c
			public const int txtTimeClose = 2131296284;
			
			// aapt resource value: 0x7f09001b
			public const int txtTimeOpen = 2131296283;
			
			// aapt resource value: 0x7f090014
			public const int txtTimer = 2131296276;
			
			// aapt resource value: 0x7f090001
			public const int txtUser = 2131296257;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_login = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int dialog_about = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_lighting = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dialog_shutter = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int fragment_devices = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int item_device = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070006
			public const int About = 2131165190;
			
			// aapt resource value: 0x7f070010
			public const int AboutAlmue = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int AboutCredits = 2131165201;
			
			// aapt resource value: 0x7f070000
			public const int BrokerAddress = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int CloseAll = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int CloseTime = 2131165199;
			
			// aapt resource value: 0x7f070018
			public const int Closed = 2131165208;
			
			// aapt resource value: 0x7f070013
			public const int ConnectionLost = 2131165203;
			
			// aapt resource value: 0x7f07000c
			public const int Disabled = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int Enable = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int Enabled = 2131165195;
			
			// aapt resource value: 0x7f070007
			public const int Exit = 2131165191;
			
			// aapt resource value: 0x7f07001b
			public const int FailState = 2131165211;
			
			// aapt resource value: 0x7f070012
			public const int FailedToConnect = 2131165202;
			
			// aapt resource value: 0x7f070003
			public const int Login = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int Logout = 2131165189;
			
			// aapt resource value: 0x7f07001a
			public const int Off = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int On = 2131165209;
			
			// aapt resource value: 0x7f070008
			public const int OpenAll = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int OpenTime = 2131165198;
			
			// aapt resource value: 0x7f070017
			public const int Opened = 2131165207;
			
			// aapt resource value: 0x7f070002
			public const int Password = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int SaveLogin = 2131165188;
			
			// aapt resource value: 0x7f070015
			public const int SetupCloseTime = 2131165205;
			
			// aapt resource value: 0x7f070014
			public const int SetupOpenTime = 2131165204;
			
			// aapt resource value: 0x7f070016
			public const int ShutterDialogException = 2131165206;
			
			// aapt resource value: 0x7f07000d
			public const int Timer = 2131165197;
			
			// aapt resource value: 0x7f07001c
			public const int Undefinded = 2131165212;
			
			// aapt resource value: 0x7f070001
			public const int Username = 2131165185;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
